-- Migration: 001_initial_schema.sql
-- This file contains the initial database schema
-- Execute this manually or use drizzle-kit to apply migrations

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- This migration file is a placeholder
-- The actual schema is defined in src/db/schema.ts and will be generated by drizzle-kit
-- Run: npm run db:generate && npm run db:migrate