name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]


jobs:
  # Fast verification job - runs first without waiting for DB setup
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Debug - List files
        run: ls -la
      
      - name: Type check
        run: npm run typecheck
      
      - name: Lint code
        run: npm run lint
      
      - name: Run unit tests
        run: npm run test:unit
      
      - name: Build project
        run: npm run build

  # Integration tests with Postgres service
  integration:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Setup test database
        env:
          NODE_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/overtime_tracker_test
          TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/overtime_tracker_test
        run: |
          # Create test database and run migrations
          PGPASSWORD=postgres createdb -h localhost -U postgres overtime_tracker_test || true
          DATABASE_URL=postgres://postgres:postgres@localhost:5432/overtime_tracker_test npm run db:migrate
      
      - name: Run integration tests
        env:
          NODE_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/overtime_tracker_test
          TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/overtime_tracker_test
        run: npm run test:integration

  # E2E tests with Postgres service
  e2e:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Setup test database
        env:
          NODE_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/overtime_tracker_test
          TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/overtime_tracker_test
        run: |
          # Create test database and run migrations
          PGPASSWORD=postgres createdb -h localhost -U postgres overtime_tracker_test || true
          DATABASE_URL=postgres://postgres:postgres@localhost:5432/overtime_tracker_test npm run db:migrate
      
      - name: Run e2e tests
        env:
          NODE_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/overtime_tracker_test
          TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/overtime_tracker_test
        run: npm run test:e2e